person_gestures = [
    "person raising their right arm",
    "person raising their left arm",
    "person waving their right hand",
    "person waving their left hand",
    "person pointing to the left",
    "person pointing to the right",
    "person pointing forward",
    "person pointing upward",
    "person crossing their arms",
    "person giving the V sign",
    "person clapping hands",
    "person giving a thumbs up",
    "person giving a thumbs down",
    "person holding both hands up",
    "person showing number one with fingers",
    "person showing number two with fingers",
    "person showing number three with fingers",
    "person putting hands on hips",
    "person scratching their head",
    "person looking up",
    "person looking down",
    "person looking to the left",
    "person looking to the right",
    "person turning around",
    "person leaning forward",
    "person leaning back",
    "person making a heart sign with hands",
    "person covering their face",
    "person shaking hands",
    "person making a stop gesture",
    "person folding their hands",
    "person saluting",
    "person dancing",
    "person snapping fingers",
    "person hugging someone",
    "person pretending to hold something",
    "person pretending to drink",
    "person sitting cross-legged",
    "person giving a high five"
]
