human_poses = [
    "sitting people",
    "standing people",
    "walking people",
    "running people",
    "squatting people",
    "kneeling people",
    "lying down people",
    "jumping people",
    "stretching people",
    "people raising right hand",
    "people raising left hand",
    "people crossing arms",
    "people waving hand",
    "people clapping hands",
    "people pointing to the left",
    "people pointing to the right",
    "people pointing forward",
    "people pointing upward",
    "people making a V sign",
    "people holding something",
    "people reading a book",
    "people looking down",
    "people looking up",
    "people looking back",
    "people turning left",
    "people turning right",
    "people with arms on hips",
    "people with hands in pockets",
    "people shaking hands",
    "people carrying a bag"
]
