robot_question_topics = [
    "something about yourself",
    "what day today is",
    "what day tomorrow is",
    "where RoboCup is held this year",
    "what the result of 3 plus 5 is",
    "your team's name",
    "where you come from",
    "what the weather is like today",
    "what the time is",
    "your favorite color",
    "your favorite object",
    "who built you",
    "what your mission is",
    "how old you are",
    "what languages you speak",
    "if you like working with humans",
    "if you can dance",
    "if you can sing",
    "if you can help me with homework",
    "if you know any jokes",
    "how many team members you have",
    "how many tasks you can do",
    "where your home base is",
    "who named you",
    "what your name means",
    "how many times you've joined RoboCup",
    "what your favorite task is",
    "if you like music",
    "if you have a birthday",
    "what country your team is from"
]
